/**
 * hanziData.js — Master character database
 * Vercel API routes use CommonJS; this file exports via module.exports.
 */

const hanziData = [
  // == NÚMEROS E FORMAS BÁSICAS ==
  { id: '一', pinyin: 'yī', meaning: 'one', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '二', pinyin: 'èr', meaning: 'two', hsk: 1, components: ['一'], visual_parents: ['一'], tags: ['numero'] },
  { id: '三', pinyin: 'sān', meaning: 'three', hsk: 1, components: ['一', '二'], visual_parents: ['二'], tags: ['numero'] },
  { id: '四', pinyin: 'sì', meaning: 'four', hsk: 1, components: ['口'], visual_parents: ['口'], tags: ['numero'] },
  { id: '五', pinyin: 'wǔ', meaning: 'five', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '六', pinyin: 'liù', meaning: 'six', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '七', pinyin: 'qī', meaning: 'seven', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '八', pinyin: 'bā', meaning: 'eight', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '九', pinyin: 'jiǔ', meaning: 'nine', hsk: 1, components: [], visual_parents: [], tags: ['numero'] },
  { id: '十', pinyin: 'shí', meaning: 'ten', hsk: 1, components: [], visual_parents: ['一'], tags: ['numero'] },
  { id: '百', pinyin: 'bǎi', meaning: 'hundred', hsk: 1, components: ['一', '白'], visual_parents: ['十'], tags: ['numero'] },
  { id: '千', pinyin: 'qiān', meaning: 'thousand', hsk: 2, components: ['人', '十'], visual_parents: ['十'], tags: ['numero'] },
  { id: '万', pinyin: 'wàn', meaning: 'ten thousand', hsk: 2, components: [], visual_parents: [], tags: ['numero'] },

  // == BOCA E DERIVADOS ==
  { id: '口', pinyin: 'kǒu', meaning: 'mouth', hsk: 1, components: [], visual_parents: [], tags: ['pessoa'] },
  { id: '日', pinyin: 'rì', meaning: 'sun / day', hsk: 1, components: [], visual_parents: ['口'], tags: ['tempo', 'natureza', 'clima'] },
  { id: '月', pinyin: 'yuè', meaning: 'moon / month', hsk: 1, components: [], visual_parents: ['日'], tags: ['tempo', 'natureza'] },
  { id: '明', pinyin: 'míng', meaning: 'bright / clear', hsk: 2, components: ['日', '月'], visual_parents: ['日'], tags: ['tempo', 'natureza'] },
  { id: '早', pinyin: 'zǎo', meaning: 'early / morning', hsk: 1, components: ['日', '十'], visual_parents: ['日'], tags: ['tempo'] },
  { id: '星', pinyin: 'xīng', meaning: 'star', hsk: 1, components: ['日'], visual_parents: ['日'], tags: ['natureza', 'clima', 'tempo'] },
  { id: '晚', pinyin: 'wǎn', meaning: 'evening / late', hsk: 1, components: ['日'], visual_parents: ['日'], tags: ['tempo'] },
  { id: '时', pinyin: 'shí', meaning: 'time / hour', hsk: 1, components: ['日'], visual_parents: ['日'], tags: ['tempo'] },

  // == ÁRVORE DA PESSOA ==
  { id: '人', pinyin: 'rén', meaning: 'person', hsk: 1, components: [], visual_parents: [], tags: ['pessoa'] },
  { id: '大', pinyin: 'dà', meaning: 'big', hsk: 1, components: ['人', '一'], visual_parents: ['人'], tags: ['pessoa'] },
  { id: '太', pinyin: 'tài', meaning: 'too much / very', hsk: 1, components: ['大'], visual_parents: ['大'], tags: ['pessoa'] },
  { id: '天', pinyin: 'tiān', meaning: 'sky / day', hsk: 1, components: ['大', '一'], visual_parents: ['大'], tags: ['natureza', 'clima', 'tempo'] },
  { id: '夫', pinyin: 'fū', meaning: 'husband', hsk: 2, components: ['大', '一'], visual_parents: ['大'], tags: ['pessoa', 'familia'] },
  { id: '从', pinyin: 'cóng', meaning: 'from / follow', hsk: 2, components: ['人'], visual_parents: ['人'], tags: ['pessoa'] },
  { id: '众', pinyin: 'zhòng', meaning: 'crowd / many', hsk: 4, components: ['人', '从'], visual_parents: ['从'], tags: ['pessoa'] },
  { id: '女', pinyin: 'nǚ', meaning: 'woman', hsk: 1, components: [], visual_parents: [], tags: ['pessoa', 'familia'] },
  { id: '子', pinyin: 'zǐ', meaning: 'child / son', hsk: 1, components: [], visual_parents: [], tags: ['pessoa', 'familia'] },
  { id: '好', pinyin: 'hǎo', meaning: 'good', hsk: 1, components: ['女', '子'], visual_parents: ['女'], tags: ['pessoa'] },
  { id: '男', pinyin: 'nán', meaning: 'man / male', hsk: 2, components: ['田', '力'], visual_parents: [], tags: ['pessoa', 'familia'] },
  { id: '父', pinyin: 'fù', meaning: 'father', hsk: 2, components: [], visual_parents: [], tags: ['pessoa', 'familia'] },
  { id: '母', pinyin: 'mǔ', meaning: 'mother', hsk: 2, components: ['女'], visual_parents: ['女'], tags: ['pessoa', 'familia'] },
  { id: '们', pinyin: 'men', meaning: 'plural suffix for people', hsk: 1, components: ['人'], visual_parents: ['人'], tags: ['pessoa'] },
  { id: '你', pinyin: 'nǐ', meaning: 'you', hsk: 1, components: ['人'], visual_parents: ['人'], tags: ['pessoa'] },
  { id: '他', pinyin: 'tā', meaning: 'he / him', hsk: 1, components: ['人'], visual_parents: ['人'], tags: ['pessoa'] },
  { id: '她', pinyin: 'tā', meaning: 'she / her', hsk: 1, components: ['女'], visual_parents: ['女'], tags: ['pessoa'] },
  { id: '我', pinyin: 'wǒ', meaning: 'I / me', hsk: 1, components: [], visual_parents: [], tags: ['pessoa'] },
  { id: '字', pinyin: 'zì', meaning: 'character / word', hsk: 1, components: ['子'], visual_parents: [], tags: ['estudo'] },
  { id: '学', pinyin: 'xué', meaning: 'to study / learn', hsk: 1, components: ['子'], visual_parents: [], tags: ['estudo'] },

  // == ÁRVORE DA NATUREZA ==
  { id: '木', pinyin: 'mù', meaning: 'wood / tree', hsk: 1, components: [], visual_parents: ['十', '人'], tags: ['natureza'] },
  { id: '林', pinyin: 'lín', meaning: 'forest (sparse)', hsk: 2, components: ['木'], visual_parents: ['木'], tags: ['natureza'] },
  { id: '森', pinyin: 'sēn', meaning: 'dense forest', hsk: 3, components: ['木', '林'], visual_parents: ['林'], tags: ['natureza'] },
  { id: '树', pinyin: 'shù', meaning: 'tree', hsk: 2, components: ['木'], visual_parents: ['木'], tags: ['natureza'] },
  { id: '土', pinyin: 'tǔ', meaning: 'earth / soil', hsk: 3, components: [], visual_parents: ['十'], tags: ['natureza'] },
  { id: '王', pinyin: 'wáng', meaning: 'king', hsk: 2, components: [], visual_parents: ['土'], tags: ['pessoa'] },
  { id: '玉', pinyin: 'yù', meaning: 'jade', hsk: 3, components: ['王'], visual_parents: ['王'], tags: ['natureza'] },
  { id: '国', pinyin: 'guó', meaning: 'country / nation', hsk: 1, components: ['口', '玉'], visual_parents: ['口'], tags: ['lugar'] },
  { id: '田', pinyin: 'tián', meaning: 'field / farmland', hsk: 2, components: [], visual_parents: ['口', '十'], tags: ['natureza'] },
  { id: '水', pinyin: 'shuǐ', meaning: 'water', hsk: 1, components: [], visual_parents: [], tags: ['natureza', 'cozinha', 'clima'] },
  { id: '火', pinyin: 'huǒ', meaning: 'fire', hsk: 1, components: [], visual_parents: ['人'], tags: ['natureza', 'cozinha'] },
  { id: '山', pinyin: 'shān', meaning: 'mountain', hsk: 1, components: [], visual_parents: [], tags: ['natureza'] },
  { id: '石', pinyin: 'shí', meaning: 'stone / rock', hsk: 3, components: [], visual_parents: ['山'], tags: ['natureza'] },
  { id: '花', pinyin: 'huā', meaning: 'flower', hsk: 2, components: [], visual_parents: [], tags: ['natureza'] },
  { id: '草', pinyin: 'cǎo', meaning: 'grass', hsk: 3, components: [], visual_parents: [], tags: ['natureza'] },
  { id: '云', pinyin: 'yún', meaning: 'cloud', hsk: 3, components: [], visual_parents: [], tags: ['natureza', 'clima'] },
  { id: '风', pinyin: 'fēng', meaning: 'wind', hsk: 2, components: [], visual_parents: [], tags: ['natureza', 'clima'] },
  { id: '雨', pinyin: 'yǔ', meaning: 'rain', hsk: 1, components: [], visual_parents: [], tags: ['natureza', 'clima'] },
  { id: '雪', pinyin: 'xuě', meaning: 'snow', hsk: 2, components: ['雨'], visual_parents: ['雨'], tags: ['natureza', 'clima'] },

  // == ANIMAIS ==
  { id: '牛', pinyin: 'niú', meaning: 'cow / ox', hsk: 2, components: [], visual_parents: ['十'], tags: ['natureza', 'cozinha', 'animal'] },
  { id: '羊', pinyin: 'yáng', meaning: 'sheep / goat', hsk: 3, components: [], visual_parents: [], tags: ['natureza', 'cozinha', 'animal'] },
  { id: '马', pinyin: 'mǎ', meaning: 'horse', hsk: 3, components: [], visual_parents: [], tags: ['natureza', 'animal'] },
  { id: '鱼', pinyin: 'yú', meaning: 'fish', hsk: 2, components: [], visual_parents: [], tags: ['natureza', 'cozinha', 'animal'] },
  { id: '鸟', pinyin: 'niǎo', meaning: 'bird', hsk: 3, components: [], visual_parents: [], tags: ['natureza', 'animal'] },
  { id: '猫', pinyin: 'māo', meaning: 'cat', hsk: 2, components: [], visual_parents: [], tags: ['animal'] },
  { id: '狗', pinyin: 'gǒu', meaning: 'dog', hsk: 2, components: [], visual_parents: [], tags: ['animal'] },

  // == COZINHA E ALIMENTAÇÃO ==
  { id: '果', pinyin: 'guǒ', meaning: 'fruit / result', hsk: 1, components: ['木', '田'], visual_parents: ['木'], tags: ['comida', 'cozinha', 'natureza'] },
  { id: '茶', pinyin: 'chá', meaning: 'tea', hsk: 1, components: ['人', '木'], visual_parents: ['木'], tags: ['comida', 'cozinha'] },
  { id: '肉', pinyin: 'ròu', meaning: 'meat / flesh', hsk: 2, components: [], visual_parents: [], tags: ['comida', 'cozinha'] },
  { id: '米', pinyin: 'mǐ', meaning: 'rice / meter', hsk: 2, components: [], visual_parents: [], tags: ['comida', 'cozinha'] },
  { id: '饭', pinyin: 'fàn', meaning: 'cooked rice / meal', hsk: 1, components: ['米'], visual_parents: ['米'], tags: ['comida', 'cozinha'] },
  { id: '吃', pinyin: 'chī', meaning: 'to eat', hsk: 1, components: ['口'], visual_parents: ['口'], tags: ['comida', 'cozinha'] },
  { id: '喝', pinyin: 'hē', meaning: 'to drink', hsk: 1, components: ['口'], visual_parents: ['口'], tags: ['comida', 'cozinha'] },
  { id: '菜', pinyin: 'cài', meaning: 'vegetable / dish', hsk: 1, components: [], visual_parents: [], tags: ['comida', 'cozinha'] },
  { id: '蛋', pinyin: 'dàn', meaning: 'egg', hsk: 2, components: [], visual_parents: [], tags: ['comida', 'cozinha'] },
  { id: '盐', pinyin: 'yán', meaning: 'salt', hsk: 4, components: [], visual_parents: [], tags: ['cozinha'] },
  { id: '糖', pinyin: 'táng', meaning: 'sugar / candy', hsk: 3, components: ['米'], visual_parents: ['米'], tags: ['comida', 'cozinha'] },
  { id: '酒', pinyin: 'jiǔ', meaning: 'alcohol / wine', hsk: 2, components: ['水'], visual_parents: ['水'], tags: ['comida', 'cozinha'] },
  { id: '面', pinyin: 'miàn', meaning: 'noodles / face / side', hsk: 2, components: [], visual_parents: [], tags: ['comida', 'cozinha'] },
  { id: '包', pinyin: 'bāo', meaning: 'bag / bread / wrap', hsk: 2, components: ['人'], visual_parents: ['人'], tags: ['comida', 'cozinha'] },
  { id: '豆', pinyin: 'dòu', meaning: 'bean / legume', hsk: 3, components: [], visual_parents: [], tags: ['comida', 'cozinha', 'natureza'] },
  { id: '油', pinyin: 'yóu', meaning: 'oil', hsk: 3, components: ['水'], visual_parents: ['水'], tags: ['cozinha'] },
  { id: '锅', pinyin: 'guō', meaning: 'pot / wok', hsk: 3, components: [], visual_parents: [], tags: ['cozinha'] },

  // == LUGAR E ESPAÇO ==
  { id: '上', pinyin: 'shàng', meaning: 'up / above / on', hsk: 1, components: ['一'], visual_parents: ['一'], tags: ['lugar', 'direcao'] },
  { id: '下', pinyin: 'xià', meaning: 'down / below / under', hsk: 1, components: ['一'], visual_parents: ['一'], tags: ['lugar', 'direcao'] },
  { id: '中', pinyin: 'zhōng', meaning: 'middle / center / China', hsk: 1, components: ['口', '一'], visual_parents: ['口'], tags: ['lugar'] },
  { id: '里', pinyin: 'lǐ', meaning: 'inside / mile', hsk: 1, components: ['土'], visual_parents: [], tags: ['lugar'] },
  { id: '外', pinyin: 'wài', meaning: 'outside / foreign', hsk: 2, components: [], visual_parents: [], tags: ['lugar'] },
  { id: '左', pinyin: 'zuǒ', meaning: 'left', hsk: 2, components: [], visual_parents: [], tags: ['direcao'] },
  { id: '右', pinyin: 'yòu', meaning: 'right', hsk: 2, components: [], visual_parents: [], tags: ['direcao'] },
  { id: '前', pinyin: 'qián', meaning: 'front / before', hsk: 2, components: [], visual_parents: [], tags: ['direcao', 'tempo'] },
  { id: '后', pinyin: 'hòu', meaning: 'back / after', hsk: 2, components: [], visual_parents: [], tags: ['direcao', 'tempo'] },
  { id: '家', pinyin: 'jiā', meaning: 'home / family', hsk: 1, components: ['子'], visual_parents: [], tags: ['lugar', 'familia'] },
  { id: '门', pinyin: 'mén', meaning: 'door / gate', hsk: 2, components: [], visual_parents: [], tags: ['lugar'] },
  { id: '城', pinyin: 'chéng', meaning: 'city / town', hsk: 2, components: ['土'], visual_parents: ['土'], tags: ['lugar'] },
  { id: '路', pinyin: 'lù', meaning: 'road / path', hsk: 1, components: [], visual_parents: [], tags: ['lugar'] },
  { id: '河', pinyin: 'hé', meaning: 'river', hsk: 2, components: ['水'], visual_parents: ['水'], tags: ['lugar', 'natureza'] },
  { id: '海', pinyin: 'hǎi', meaning: 'sea / ocean', hsk: 2, components: ['水'], visual_parents: ['水'], tags: ['lugar', 'natureza'] },

  // == VERBO E AÇÃO ==
  { id: '来', pinyin: 'lái', meaning: 'to come', hsk: 1, components: [], visual_parents: ['木'], tags: ['acao'] },
  { id: '去', pinyin: 'qù', meaning: 'to go', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '说', pinyin: 'shuō', meaning: 'to speak / say', hsk: 1, components: ['口'], visual_parents: ['口'], tags: ['acao'] },
  { id: '看', pinyin: 'kàn', meaning: 'to look / watch', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '听', pinyin: 'tīng', meaning: 'to listen', hsk: 1, components: ['口'], visual_parents: ['口'], tags: ['acao'] },
  { id: '读', pinyin: 'dú', meaning: 'to read', hsk: 2, components: ['口'], visual_parents: ['口'], tags: ['acao', 'estudo'] },
  { id: '写', pinyin: 'xiě', meaning: 'to write', hsk: 1, components: [], visual_parents: [], tags: ['acao', 'estudo'] },
  { id: '走', pinyin: 'zǒu', meaning: 'to walk', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '坐', pinyin: 'zuò', meaning: 'to sit / travel by', hsk: 1, components: ['人', '土'], visual_parents: ['人'], tags: ['acao'] },
  { id: '站', pinyin: 'zhàn', meaning: 'to stand / station', hsk: 2, components: [], visual_parents: [], tags: ['acao'] },
  { id: '买', pinyin: 'mǎi', meaning: 'to buy', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '卖', pinyin: 'mài', meaning: 'to sell', hsk: 2, components: [], visual_parents: [], tags: ['acao'] },
  { id: '开', pinyin: 'kāi', meaning: 'to open / start', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '关', pinyin: 'guān', meaning: 'to close / shut', hsk: 2, components: [], visual_parents: [], tags: ['acao'] },
  { id: '打', pinyin: 'dǎ', meaning: 'to hit / make a call', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '做', pinyin: 'zuò', meaning: 'to do / make', hsk: 1, components: ['人'], visual_parents: ['人'], tags: ['acao'] },
  { id: '用', pinyin: 'yòng', meaning: 'to use', hsk: 2, components: [], visual_parents: [], tags: ['acao'] },
  { id: '给', pinyin: 'gěi', meaning: 'to give', hsk: 1, components: [], visual_parents: [], tags: ['acao'] },
  { id: '想', pinyin: 'xiǎng', meaning: 'to think / want', hsk: 1, components: ['木'], visual_parents: [], tags: ['acao'] },
  { id: '知', pinyin: 'zhī', meaning: 'to know', hsk: 2, components: ['口'], visual_parents: ['口'], tags: ['acao', 'estudo'] },
];

module.exports = { hanziData };
